exports.modalFases = [

    { faseModal: 1, titulo: 'Memória de curto prazo', frase: 'Nada mal, sua mente consegue armazenar uma informação, por um breve período de tempo muito bem!', texto: 'A memória de curta duração pode ser definida como o mecanismo da memória que nos permite reter uma determinada quantidade de informação durante um período curto de tempo, que varia entre 30 segundos a 5 minutos.', urlimg: '../../assets/img/fase1.png' },
    { faseModal: 2, titulo: 'Cadeia de sinapses', frase: 'Suas conexões neurais e suas sinapses estão trabalhando a todo vapor, aí sim!', texto: 'As sinapses não são nada mais que conexões entre os neurônios onde agem como transmissoras de impulsos nervosos de um neurônio para outro.', urlimg: '../../assets/img/fase2.png' },
    { faseModal: 3, titulo: 'Bainha de Mielina', frase: 'Pois é, a conexão estre seus neorônios está sendo protegida e agilizada muito bem pela sua Bainha de Mielina, continue assim!', texto: 'A Bainha de Mielina é uma estrutura que atua na proteação e no isolamento elétrico nas sinapses entre os neurônios, além de aprimorar a velocidade dessas conexões.', urlimg: '../../assets/img/fase3.png' },
    { faseModal: 4, titulo: 'Lobo temporal', frase: 'Uou, parece que seu Lobo Temporal, que facilita a síntese de memórias e concretiza o nosso sistema memorial, está cumprindo seu papel!', texto: 'Basicamente o Lobo Temporal, que se localiza na lateral do cérebro, é responsável pelo gerenciamento e formação de memórias.', urlimg: '../../assets/img/fase4.png' },
    { faseModal: 5, titulo: 'Massa Cinzenta', frase: 'Incrível! Seu cérebro está se tornando uma máquina super potente, você obteve o controle total de seu cérebro!', texto: 'O Cérebro é o orgão mais incrível do corpo humano, ele é responsável por tornar-nos quem somos e o que pensamos, além de atuar em milhares de outras atividades.', urlimg: '' },
    { faseModal: 6, titulo: 'Encéfalo', frase: 'Parabéns, você venceu! Seu encéfalo trabalha perfeitamente, sua conexão entre o Cérebro, o Cerebelo e o Tronco Encefálico é magnifica, agora seu QI é mais de 5000 e tem poderes telecinéticos e telepáticos.', texto: 'O Encéfalo é o conjunto do cérebro, do cerebelo e do tronco encefálico, e corresponde ao sistema nervoso central.', urlimg: '' },
]


